INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, COST_PER_NIGHT) VALUES (1,'STANDARD',300.00);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, COST_PER_NIGHT) VALUES  (2,'BUSINESS',900.00);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, COST_PER_NIGHT) VALUES (3,'BUSINESS',900.00);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, COST_PER_NIGHT) VALUES (4,'STANDARD',300.00);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, COST_PER_NIGHT) VALUES  (5,'STANDARD',300.00);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, COST_PER_NIGHT) VALUES (6,'SUITE',1300.00);